### ISSUE TITLE
Add standup meeting notes, w8

### ISSUE THREAD

**Issue by sadsoap** [cse110-sp24-group12/cse110-sp24-group12#60]
# Overview
Add meeting notes from w8, discussing updates to our progress and specifications for the check-in process/demo video.

## Frontend (UI/UX)
N/A

## Backend (CRUD operations)
N/A

## Acceptance Criteria
- [x] Write and push notes to `admin/meetings/`

**Comment by lindseyrapp** [comment]
These are great, thank you!

**Comment by lindseyrapp** [comment]
Close #60
